import type { JobOpsAppMetadata } from "./app-metadata-contract";

// This file is generated by scripts/generate-jobops-build-info.mjs.
// Do not edit by hand; rerun the build-info script instead.
export const GENERATED_JOBOPS_BUILD_INFO: JobOpsAppMetadata = {
  "appName": "JobOps",
  "releaseChannel": "alpha",
  "environment": "dev",
  "commit": "baba094",
  "fullCommit": "baba094792386144d8a66e788cb9d5066101b096",
  "buildTime": "2026-05-24T00:52:49.757Z"
};
