import type { JobOpsAppMetadata } from "./app-metadata-contract";

// This file is generated by scripts/generate-jobops-build-info.mjs.
// Do not edit by hand; rerun the build-info script instead.
export const GENERATED_JOBOPS_BUILD_INFO: JobOpsAppMetadata = {
  "appName": "JobOps",
  "releaseChannel": "alpha",
  "environment": "dev",
  "commit": "de3a323",
  "fullCommit": "de3a32300c955e73d1fdd5919628a50bd846fd9d",
  "buildTime": "2026-05-23T02:32:26.927Z"
};
