import type { JobOpsAppMetadata } from "./app-metadata-contract";

// This file is generated by scripts/generate-jobops-build-info.mjs.
// Do not edit by hand; rerun the build-info script instead.
export const GENERATED_JOBOPS_BUILD_INFO: JobOpsAppMetadata = {
  "appName": "JobOps",
  "releaseChannel": "alpha",
  "environment": "dev",
  "commit": "b50142c",
  "fullCommit": "b50142cbe7da3743581b007d53822865e558756d",
  "buildTime": "2026-05-22T20:08:08.510Z"
};
